### ISSUE TITLE
automanifest in Makefile.PL

### ISSUE THREAD

**Issue by jimeUWOshkosh** [rbwohlfarth/ETL-Pipeline#2] opened 2019-06-03 02:16 UTC
Halo

$ perl Makefile.PL
Whines that automanifest can not be used with 'strict'
I'm not an expert with inc::Module::Install and strict but you could use

no strict;
auto_manifest;
use strict;

to get over this temporary issue.

Have a great day!

**Comment by rbwohlfarth** [comment] 2021-07-18 22:52
I wasn't able to reproduce the warning message. No change made. Maybe upgrade `Module::Install` or `Module::Install::AutoManifest`?

**Comment by rbwohlfarth** [comment] 2021-07-19 14:34
Recreated this in a brand new Perl install. You need to install **Module::Install::AutoManifest** like so - `cpanm Module::Install::AutoManifest`.

I tried using **configure_requires**, but that didn't help. Also tried `BEGIN { configure_requires 'Module::Install::AutoManifest'; }`. Both options still fail at the compile stage. Replaced `auto_manifest;` with `auto_manifest();`. That just changed the error message to _unknown function_. The problem is that compile time happens before there is any check for this missing module.

**Comment by rbwohlfarth** [comment] 2021-08-24 17:32
Maybe add **inc/** to the repository? Then the install modules would follow the code around.

**Comment by rbwohlfarth** [comment] 2021-09-18 20:16
Fixed by commit 995253bbc30fd97feab846fb6baa3c5a9973fcad

**Closed as completed by rbwohlfarth** 2021-09-18 20:16 UTC
